nombre = "Juan Cruz"
apellido = "Gonzalez"
estudiante = nombre + " " + apellido
estudianteMayus = estudiante.toUpperCase()
estudianteMinus = estudiante.toLowerCase()
let longitud_estudiante = estudiante.length
primera_letra_nombre = nombre[0]
ultima_letra_apellido = apellido[7]
sin_espacios_estudiante = estudiante.trim()
nombre_en_estudiante = estudiante.includes("Juan")
